describe('Check From Input', () => {
    it('Interact with input and submit form', () => {
      cy.visit('http://localhost:3000/')

      cy.get('[data-cy="form-input"]').should('exist')
      cy.get('[data-cy="heading1-forminput"]').should('exist')
      cy.get('[data-cy="paragraph1-forminput"]').should('exist')
      cy.get('[data-cy="svg1-forminput"]').should('exist')
      cy.get('[data-cy="input-forminput-name"]').should('exist').type('joe')
      cy.get('[data-cy="svg2-forminput"]').should('exist')
      cy.get('[data-cy="input-forminput-email"]').should('exist').type('joe@leroi.com')
      cy.get('[data-cy="svg3-forminput"]').should('exist')
      cy.get('[data-cy="input-forminput-password"]').should('exist').type('Godisgreat')
      cy.get('[data-cy="svg4-forminput"]').should('exist')
      cy.get('[data-cy="select-forminput-occupation"]').should('exist').select(2)
      cy.get('[data-cy="svg5-forminput"]').should('exist')
      cy.get('[data-cy="select-forminput-states"]').should('exist').select('Arizona AZ')
      cy.get('[data-cy="button-forminput-submit"]').should('exist').click()
      cy.get('[data-cy="heading2-forminput-success"]').should('exist')
    })

    it('Checking errors',()=>{
        cy.visit('http://localhost:3000/')
        cy.get('[data-cy="input-forminput-name"]').should('exist').type('j').as('name-input')
        cy.get('[data-cy="button-forminput-submit"]').should('exist').click().as('button-submit')
        cy.get('[data-cy="error-forminput-name"]').should('not.be.hidden').as('error-name')
        cy.get('@name-input').clear()
        cy.get('@name-input').type('bob')
        cy.get('@button-submit').click()
        cy.get('@error-name').should('be.hidden')
        cy.get('[data-cy="error-forminput-email"]').should('not.be.hidden').as('error-email')
        cy.get('[data-cy="input-forminput-email"]').type('mo').as('email-input')
        cy.get('@error-email').should('not.be.hidden')
        cy.get('@email-input').clear().type('mother')
        cy.get('@button-submit').click()
        cy.get('@error-email').should('not.be.hidden')
        cy.get('@email-input').clear().type('mother@gmail.com')
        cy.get('@button-submit').click()
        cy.get('[data-cy="error-forminput-password"]').should('not.be.hidden').as('error-password')
        cy.get('[data-cy="input-forminput-password"]').should('exist').as('password-input')
        cy.get('@password-input').type('123456gsgsdg')
        cy.get('@button-submit').click()
        cy.get('@error-password').should('be.hidden')
        cy.get('[data-cy="error-forminput-occupation"]').should('not.be.hidden').as('error-occupation')
        cy.get('[data-cy="select-forminput-occupation"]').select(2)
        cy.get('@button-submit').click()
        cy.get('@error-occupation').should('be.hidden')
        cy.get('[data-cy="heading2-forminput-success"]').should('exist')
    })
  })